# Generated by Django 4.2.3 on 2023-11-16 17:54
from django.db import migrations

def create_hostels(apps, schema_editor):
    Hostel = apps.get_model('room', 'Hostel')
    Hostel.objects.create(name='BH1', capacity=300)
    Hostel.objects.create(name='GH1', capacity=300)
    Hostel.objects.create(name='BH2', capacity=300)
    Hostel.objects.create(name='GH2', capacity=300)

class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),  # Replace '000y_previous_migration' with the previous migration's name
    ]

    operations = [
        migrations.RunPython(create_hostels),
    ]