# Generated by Django 4.2.3 on 2023-11-16 17:56
from django.db import migrations


def create_initial_counter(apps, schema_editor):
        ReceiptNumberCounter = apps.get_model('room', 'ReceiptNumberCounter')
        ReceiptNumberCounter.objects.create(counter=1)
    
class Migration(migrations.Migration):
    
        dependencies = [
            ('room', '0002_auto_20231116_2324'),# Update this with the actual dependency
        ]
    
        operations = [
            migrations.RunPython(create_initial_counter),
        ] 